### ISSUE TITLE
新版的客户端似乎无效了

### ISSUE THREAD

**Issue by kbj** [Fuduji95/TGRepeat#4]
10.6.2版本，防撤回已无效了。作者有兴趣适配一下新版吗？

**Comment by Fuduji95** [comment]
不再适配了哦，因为是练习用的，貌似有功能更完善的插件了https://github.com/EasyAuthorize/TgPlus

**Comment by kbj** [comment]
好的，谢谢作者

**Comment by Fuduji95** [comment]
或者在TG里面搜索1TH pro 防撤回也挺好用的
